ERROR [2022-12-14 22:03:33,350][D:\phasell_on_python_2\airline\AVB\service.py service(25):add_on][6664]:Traceback (most recent call last):
  File "D:\phasell_on_python_2\airline\AVB\service.py", line 14, in add_on
    app.bookingAvailability(holdTask)
  File "D:\phasell_on_python_2\airline\AVB\AVBApp.py", line 70, in bookingAvailability
    resp = self.post(url, headers=headers, json=data)
  File "D:\pythonProject\venv\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\phasell_on_python_2\airline\base.py", line 356, in request
    raise HttpRetryMaxException(msg)
airline.base.HttpRetryMaxException: Object of type UUID is not JSON serializable

ERROR [2022-12-14 22:05:17,387][D:\phasell_on_python_2\airline\AVB\service.py service(25):add_on][9244]:Traceback (most recent call last):
  File "D:\phasell_on_python_2\airline\AVB\service.py", line 14, in add_on
    app.bookingAvailability(holdTask)
  File "D:\phasell_on_python_2\airline\AVB\AVBApp.py", line 74, in bookingAvailability
    raise Exception(f"[resp] ==> {resp.status_code}")
Exception: [resp] ==> 403

ERROR [2022-12-14 22:13:30,632][D:\phasell_on_python_2\airline\AVB\service.py service(25):add_on][4908]:Traceback (most recent call last):
  File "D:\phasell_on_python_2\airline\AVB\service.py", line 15, in add_on
    flight = app.convert_search()
  File "D:\phasell_on_python_2\airline\AVB\AVBApp.py", line 131, in convert_search
    list(ths.map(func,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\phasell_on_python_2\airline\AVB\AVBApp.py", line 115, in func
    'adultPrice': journey['fares'][0]['fare']['amount'] or journey['fares'],
IndexError: list index out of range

ERROR [2022-12-14 22:29:40,181][D:\phasell_on_python_2\airline\AVB\service.py service(25):add_on][8656]:Traceback (most recent call last):
  File "D:\phasell_on_python_2\airline\AVB\service.py", line 14, in add_on
    app.bookingAvailability(holdTask)
  File "D:\phasell_on_python_2\airline\AVB\AVBApp.py", line 75, in bookingAvailability
    raise Exception(f"[resp] ==> {resp.status_code}")
Exception: [resp] ==> 403

