ERROR [2022-12-19 09:39:47,063][D:\phasell_on_python_2\airline\AXY\service.py service(27):add_on][8012]:Traceback (most recent call last):
  File "D:\phasell_on_python_2\airline\AXY\service.py", line 15, in add_on
    app.bookingAvailability(holdTask, token)
  File "D:\phasell_on_python_2\airline\AXY\AXYApp.py", line 102, in bookingAvailability
    self.currencyCode = resp.json()['data']['currencyCode']
KeyError: 'data'

